# 基于官方Spark 4.0.0镜像
FROM apache/spark:4.0.0

USER root


RUN pip3 install --no-cache-dir pandas pyarrow \
    -i https://pypi.tuna.tsinghua.edu.cn/simple \
    --trusted-host pypi.tuna.tsinghua.edu.cn



    